/* IN THIS SECTION WE WILL TAKE AN INPUT FROM THE USER AND WILL STORE IT IN THE EXCEL SHEET.
IT IS STATED THAT THIS SECTION IS ONLY TO MAKE A SKELETON TO STORE DATA IN THE EXCEL SHEET.
AND OF COURSE WE WILL UPDATE IT SOONER.
AGAIN I WILL SAY THAT I HAVE USED BASIC CONCEPTS TO CODE IT. 
BUT HERE WE ARE INTRODUCED WITH SOME NEW THINGS, WHICH YOU GUYS BETTER KNOWS.
IT IS STATED THAT NO OBJECT-ORIENTED CONCEPT WILL  BE USED IN THIS PROJECT. 
THIS CODE IS ONLY FOR 
1.UMER ZULFIQAR 
2.AMAN MIRZA
3.SUBHAN ALI 
4.WALEED IMRAN 
5.MUHAMMAD HASSAN
ALL OF THE CODE I HAVE DONE AS A PUBLIC REPOSITORY WITH THE NAME OF "MY-PROJECTS1" IS ONLY AND ONLY
FOR THESE FIVE PEOPLE, AS IT IS ACCORDING TO OUR REQUIRMENTS.😊  */
#include<iostream>
#include<iomanip>
#include<fstream>
#include<string>
using namespace std;
int main()
{
    ofstream outData;
    string s;
    cin>>s;

    int n=1;

    outData.open("outfile.csv",ios::app);
    outData<<s<<endl;
    outData<<n<<endl;
    system("pause");
    return 0;
} 